Pedram/feature/add booking/form
HadikaMalik/React-Module-Project pull request #55
Opened 2024-03-18 18:26 UTC by pedram-am

This introduces a new feature to the Bookings component, enabling users to add bookings via a form. The form includes input fields for first name, last name, email, title, room ID, check-in date, and check-out date. Also, resolves an issue where the last name (surname) field was not displayed in the booking table, by updating "surname" to "lastName" in the Booking.jsx file.

2024-03-20 22:32 UTC, HadikaMalik requested changes
Can we leave the surname as surname and not change it to lastName? I am asking becasue the data we are fetching, that has surname, and everything is implemented with surname. So if we change this here, then we will have to change it everywhere else as well. Let me know, until then I won't merge it. :)

2024-03-21 08:10 UTC, PERicci commented on src/components/Booking/Booking.jsx
> -  const { id, title, firstName, surname, email, roomId, checkInDate, checkOutDate } = props.booking;
I suggest keeping the surname the same. It matches how we've done things in other parts of the app and stays true to the original data. This way, everything stays consistent and follows the same pattern.

2024-03-21 08:14 UTC, PERicci requested changes
The implementation is working well. The only tweak I'd suggest is reverting the property name from 'lastName' back to 'surname'. It's consistent with other components and aligns with the original data. Also, 'surname' feels more fitting, especially for people with multiple surnames.

2024-03-21 08:16 UTC, PERicci commented
We may need to make some adjustments due to the implementation of the search functionality. I think it would be easier to address these after merging.

2024-03-21 17:23 UTC, pedram-am commented
Hi, thank you for your feedback! We've decided to stick with 'surname' as it helps to keep things consistent and makes the work easier. I've gone ahead and updated the Bookings.jsx file accordingly. Thanks again! 👍

2024-03-27 08:10 UTC, PERicci approved these changes
Merged the changes after resolving conflicts.

2024-03-27 08:13 UTC, PERicci approved these changes

2024-04-04 01:24 UTC, merged